platform :ios, '9.0'

target 'Herby' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'SwiftyJSON'

  # Pods for Herby

  target 'HerbyTests' do
    inherit! :search_paths
    pod 'Alamofire'
  end

  target 'HerbyUITests' do
    # Pods for testing
    pod 'Alamofire'
  end

end
