platform :ios, '10.0'

target 'Herby' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Herby

  target 'HerbyTests' do
  
    pod 'Alamofire', '~> 5.0.0-rc.2'
    # Pods for testing
  end



end
